name: ai_bot

services:
  ai_bot:
    container_name: ai_bot
    image: ghcr.io/operkh/ai_bot
    env_file:
      - .env
    volumes:
      - /srv/appdata/ai_bot/data:/app/data
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: ai_bot_postgres
    image: tensorchord/vchord-postgres:pg16-v0.5.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /srv/appdata/ai_bot/postgresql:/var/lib/postgresql/data
    restart: always
